### ISSUE TITLE
repo is big

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-project-analytics#32]
This repo is quite big, and it appears this is due to caching the results in the data folder. This is causing a problem for me now because I am having trouble cloning the repo, which is necessary to install this repo, which is necessary to run the html generation for nwb-overview. Would it be possible to cache these results somewhere else? Perhaps we could store them in a separate GitHub repo. Then we'd need to mess with the git commit history of this repo to reduce the size.

**Comment by oruebel** [comment]
Closing this issue for now.
